CREATE TABLE IF NOT EXISTS rrhh_sueldos_periodo_ajustes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  personal_id INT NOT NULL,
  sucursal_id INT NOT NULL,
  mes TINYINT UNSIGNED NOT NULL,
  anio SMALLINT UNSIGNED NOT NULL,
  aplica_valor_hora TINYINT(1) NOT NULL DEFAULT 1,
  aplica_sueldo_basico_escala TINYINT(1) NOT NULL DEFAULT 1,
  aplica_horas_extra TINYINT(1) NOT NULL DEFAULT 0,
  aplica_incentivos TINYINT(1) NOT NULL DEFAULT 1,
  aplica_banco TINYINT(1) NOT NULL DEFAULT 0,
  hs_realizadas_mes DECIMAL(10, 2) NULL DEFAULT NULL,
  valor_hora DECIMAL(12, 2) NULL DEFAULT NULL,
  sueldo_basico DECIMAL(12, 2) NULL DEFAULT NULL,
  horas_extra_50 DECIMAL(12, 2) NULL DEFAULT NULL,
  horas_extra_hs DECIMAL(10, 2) NULL DEFAULT NULL,
  horas_feriado DECIMAL(12, 2) NULL DEFAULT NULL,
  horas_feriado_hs DECIMAL(10, 2) NULL DEFAULT NULL,
  incentivos DECIMAL(12, 2) NULL DEFAULT NULL,
  incentivos_seleccionados TEXT NULL DEFAULT NULL,
  extras DECIMAL(12, 2) NULL DEFAULT NULL,
  ausencias_justificadas DECIMAL(10, 2) NULL DEFAULT NULL,
  ausencias_injustificadas DECIMAL(10, 2) NULL DEFAULT NULL,
  tardanzas DECIMAL(10, 2) NULL DEFAULT NULL,
  descuentos DECIMAL(12, 2) NULL DEFAULT NULL,
  adelantos DECIMAL(12, 2) NULL DEFAULT NULL,
  sueldo_sac DECIMAL(12, 2) NULL DEFAULT NULL,
  sueldo_neto DECIMAL(12, 2) NULL DEFAULT NULL,
  banco DECIMAL(12, 2) NULL DEFAULT NULL,
  efectivo DECIMAL(12, 2) NULL DEFAULT NULL,
  fecha_deposito DATE NULL DEFAULT NULL,
  sueldo_pagado TINYINT(1) NOT NULL DEFAULT 0,
  comentario_cobro TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY rrhh_sueldos_ajuste_periodo_unique (personal_id, mes, anio),
  KEY idx_rrhh_sueldos_ajuste_sucursal_periodo (sucursal_id, mes, anio),
  CONSTRAINT fk_rrhh_sueldos_ajuste_personal FOREIGN KEY (personal_id) REFERENCES personal(id) ON DELETE CASCADE,
  CONSTRAINT fk_rrhh_sueldos_ajuste_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
