-- RH-LiqFinal: Ajustes de simulación para liquidaciones finales

CREATE TABLE `rrhh_liquidaciones_finales_ajustes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `liquidacion_id` int NOT NULL,
  `aplica_valor_hora` tinyint(1) DEFAULT 0,
  `aplica_sueldo_basico_escala` tinyint(1) DEFAULT 1,
  `aplica_banco` tinyint(1) DEFAULT 1,
  `aplica_horas_extra` tinyint(1) DEFAULT 0,
  `aplica_incentivos` tinyint(1) DEFAULT 1,
  `valor_hora` decimal(12,2) DEFAULT NULL,
  `sueldo_basico` decimal(12,2) DEFAULT NULL,
  `horas_extra_50` decimal(12,2) DEFAULT NULL,
  `horas_extra_hs` decimal(10,4) DEFAULT NULL,
  `horas_feriado` decimal(12,2) DEFAULT NULL,
  `horas_feriado_hs` decimal(10,4) DEFAULT NULL,
  `incentivos` decimal(12,2) DEFAULT NULL,
  `incentivos_seleccionados` json DEFAULT NULL,
  `extras` decimal(12,2) DEFAULT NULL,
  `ausencias_justificadas` decimal(12,2) DEFAULT NULL,
  `ausencias_injustificadas` decimal(12,2) DEFAULT NULL,
  `tardanzas` decimal(12,2) DEFAULT NULL,
  `descuentos` decimal(12,2) DEFAULT NULL,
  `adelantos` decimal(12,2) DEFAULT NULL,
  `sueldo_neto` decimal(12,2) DEFAULT NULL,
  `banco` decimal(12,2) DEFAULT NULL,
  `efectivo` decimal(12,2) DEFAULT NULL,
  `sac_porcentaje` decimal(8,4) DEFAULT NULL,
  `sac_importe` decimal(12,2) DEFAULT NULL,
  `vng_porcentaje` decimal(8,4) DEFAULT NULL,
  `vng_importe` decimal(12,2) DEFAULT NULL,
  `preaviso_porcentaje` decimal(8,4) DEFAULT NULL,
  `preaviso_importe` decimal(12,2) DEFAULT NULL,
  `total_liq` decimal(12,2) DEFAULT NULL,
  `liq_banco` decimal(12,2) DEFAULT NULL,
  `liq_efectivo` decimal(12,2) DEFAULT NULL,
  `total_general` decimal(12,2) DEFAULT NULL,
  `sueldo_pagado` tinyint(1) DEFAULT 0,
  `fecha_deposito` date DEFAULT NULL,
  `comentario_cobro` text DEFAULT NULL,
  `ministerio_aplica` tinyint(1) DEFAULT 0,
  `ministerio_direccion` varchar(500) DEFAULT NULL,
  `ministerio_fecha` date DEFAULT NULL,
  `ministerio_horario` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `liq_finales_ajustes_liq_id_unique` (`liquidacion_id`),
  CONSTRAINT `liq_finales_ajustes_fk` FOREIGN KEY (`liquidacion_id`) REFERENCES `rrhh_liquidaciones_finales` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
